#! /usr/bin/env ruby
# This is a wrapper around all Pivotal Authored New Relic Plugins
# See README.md for usage information
#
# The MIT License
#
# Copyright (c) 2013-2014 Pivotal Software, Inc. 
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.


require "rubygems"
require "bundler/setup"

# Load each module. There can only be one config/newrelic_plugin.xml 
# These are slightly modified to not call setup_and_run if included in another file
# without that modification this agent will break
# Adding a # in front of a require_relative line will stop that plugin from loading
# at all. Should only need to be done in extreme circumstances
## RabbitMQ Plugin
require_relative "plugins/pivotal_rabbitmq_plugin/pivotal_rabbitmq_plugin.rb"
## VFWS/Mod_BMX Plugin
require_relative "plugins/pivotal_httpd_mod_bmx_plugin/pivotal_httpd_mod_bmx_plugin.rb"
## Redis
require_relative "plugins/pivotal_redis_plugin/pivotal_redis_plugin.rb"

require "newrelic_plugin"

module PivotalAgent
  # Force the location of the config file in case we aren't invoked from the correct 
  # directory
  NewRelic::Plugin::Config.config_file=File.dirname(__FILE__) + "/config/newrelic_plugin.yml"
  # The above require_relatives will load the plugins. The next line just sets them up 
  # and runs them
  NewRelic::Plugin::Run.setup_and_run
end
